import * as fsSyncer from 'fs-syncer'
import {test, beforeEach, expect, vi as jest} from 'vitest'
import * as typegen from '../src'
import {getPureHelper} from './helper'

export const {typegenOptions, logger, poolHelper: helper} = getPureHelper({__filename})

beforeEach(async () => {
  jest.resetAllMocks()

  await helper.setupDb()
  await helper.pool.query(helper.sql`
    create table test_table(
      a int not null,
      b int
    )
  `)
})

test('primitives are non-nullable', async () => {
  const syncer = fsSyncer.testFixture({
    expect,
    targetState: {
      'index.ts': `
        import {sql} from 'slonik'

        export default [
          sql\`select 1 as a\`,
          sql\`select 'a' as a\`,
          sql\`select 'a' as b\`,
          sql\`select null::integer as b\`,
          sql\`select sum(a) from test_table\`,
          sql\`select sum(b) from test_table\`,
          sql\`select current_date\`,
          sql\`select 'foo' || 'bar'\`,
          sql\`select 'foo' || null\`,
          sql\`select a > 1 from test_table\`,
        ]
      `,
    },
  })

  syncer.sync()

  await typegen.generate(typegenOptions(syncer.baseDir))

  expect(logger.warn).not.toHaveBeenCalled()
  expect(logger.error).not.toHaveBeenCalled()

  expect(syncer.yaml()).toMatchInlineSnapshot(`
    "---
    index.ts: |-
      import {sql} from 'slonik'

      export default [
        sql<queries.A>\`select 1 as a\`,
        sql<queries.A_6>\`select 'a' as a\`,
        sql<queries.B>\`select 'a' as b\`,
        sql<queries.B_12>\`select null::integer as b\`,
        sql<queries.TestTable_sum>\`select sum(a) from test_table\`,
        sql<queries.TestTable_sum>\`select sum(b) from test_table\`,
        sql<queries.CurrentDate>\`select current_date\`,
        sql<queries.Column>\`select 'foo' || 'bar'\`,
        sql<queries.Column_2>\`select 'foo' || null\`,
        sql<queries.TestTable>\`select a > 1 from test_table\`,
      ]

      export declare namespace queries {
        // Generated by @pgkit/typegen

        /** - query: \`select 1 as a\` */
        export interface A {
          /** not null: \`true\`, regtype: \`integer\` */
          a: number
        }

        /** - query: \`select 'a' as a\` */
        export interface A_6 {
          /** not null: \`true\`, regtype: \`text\` */
          a: string
        }

        /** - query: \`select 'a' as b\` */
        export interface B {
          /** not null: \`true\`, regtype: \`text\` */
          b: string
        }

        /** - query: \`select null::integer as b\` */
        export interface B_12 {
          /** regtype: \`integer\` */
          b: number | null
        }

        /**
         * queries:
         * - \`select sum(a) from test_table\`
         * - \`select sum(b) from test_table\`
         */
        export interface TestTable_sum {
          /** regtype: \`bigint\` */
          sum: number | null
        }

        /** - query: \`select current_date\` */
        export interface CurrentDate {
          /** not null: \`true\`, regtype: \`date\` */
          current_date: Date
        }

        /** - query: \`select 'foo' || 'bar'\` */
        export interface Column {
          /** not null: \`true\`, regtype: \`text\` */
          '?column?': string
        }

        /** - query: \`select 'foo' || null\` */
        export interface Column_2 {
          /** regtype: \`text\` */
          '?column?': string | null
        }

        /** - query: \`select a > 1 from test_table\` */
        export interface TestTable {
          /** regtype: \`boolean\` */
          '?column?': boolean | null
        }
      }
    "
  `)
})
