import * as fsSyncer from 'fs-syncer'
import * as typegen from '../src'
import {getHelper} from './helper'

export const {typegenOptions, logger, poolHelper: helper} = getHelper({__filename})

test(`default type mappings`, async () => {
  const syncer = fsSyncer.jestFixture({
    targetState: {
      'index.ts': `
        import {sql} from 'slonik'

        export const mappings = sql\`
          select
            null::timestamptz as a,
            null::uuid as b,
            null::void as c,
            null::bigint as d,
            null::smallint as e,
            null::time as f,
            null::bit as g,
            null::money as h,
            null::cidr as i,
            null::float8 as j,
            null::interval as k,
            null::real as l
        \`
      `,
    },
  })

  syncer.sync()

  await typegen.generate(typegenOptions(syncer.baseDir))

  expect(logger.warn).not.toHaveBeenCalled()
  expect(logger.error).not.toHaveBeenCalled()

  expect(syncer.yaml()).toMatchInlineSnapshot(`
    "---
    index.ts: |-
      import {sql} from 'slonik'
      
      export const mappings = sql<queries.Mapping>\`
        select
          null::timestamptz as a,
          null::uuid as b,
          null::void as c,
          null::bigint as d,
          null::smallint as e,
          null::time as f,
          null::bit as g,
          null::money as h,
          null::cidr as i,
          null::float8 as j,
          null::interval as k,
          null::real as l
      \`
      
      export declare namespace queries {
        // Generated by @slonik/typegen
      
        /** - query: \`select null::timestamptz as a, null::uui... [truncated] ... j, null::interval as k, null::real as l\` */
        export interface Mapping {
          /** regtype: \`timestamp with time zone\` */
          a: number | null
      
          /** regtype: \`uuid\` */
          b: string | null
      
          /** regtype: \`void\` */
          c: void
      
          /** regtype: \`bigint\` */
          d: number | null
      
          /** regtype: \`smallint\` */
          e: number | null
      
          /** regtype: \`time without time zone\` */
          f: string | null
      
          /** regtype: \`bit(1)\` */
          g: number | null
      
          /** regtype: \`money\` */
          h: string | null
      
          /** regtype: \`cidr\` */
          i: string | null
      
          /** regtype: \`double precision\` */
          j: number | null
      
          /** regtype: \`interval\` */
          k: number | null
      
          /** regtype: \`real\` */
          l: number | null
        }
      }
      "
  `)
})
