/* eslint-disable */
// tslint:disable
// this file is generated by a tool; don't change it manually.

// bit of an edge-case, but just to be sure...
// this file should _not_ be removed

export default 123
