import {sql} from './db'

const results = await sql<queries.User>`select id, email, email_verified as all_good from users`

export declare namespace queries {
  // Generated by @pgkit/typegen

  /** - query: `select id, email, email_verified as all_good from users` */
  export interface User {
    /** column: `public.users.id`, not null: `true`, regtype: `integer` */
    id: number

    /** column: `public.users.email`, not null: `true`, regtype: `text` */
    email: string

    /** column: `public.users.email_verified`, not null: `true`, regtype: `boolean` */
    all_good: boolean
  }
}
