/* eslint-disable */
// tslint:disable
// this file is generated by a tool; don't change it manually.
import {CountInfo} from './CountInfo'
import {Foo} from './Foo'

export {CountInfo}
export {Foo}

export interface KnownTypes {
  CountInfo: CountInfo
  Foo: Foo
}

/** runtime-accessible object with phantom type information of query results. */
export const knownTypes: KnownTypes = {
  CountInfo: {} as CountInfo,
  Foo: {} as Foo,
}
