/* eslint-disable */
// tslint:disable
// this file is generated by a tool; don't change it manually.
import {CountInfo} from './CountInfo'
import {Foo} from './Foo'
import {FooSubset} from './FooSubset'

export {CountInfo}
export {Foo}
export {FooSubset}

export interface KnownTypes {
  CountInfo: CountInfo
  Foo: Foo
  FooSubset: FooSubset
}

/** runtime-accessible object with phantom type information of query results. */
export const knownTypes: KnownTypes = {
  CountInfo: {} as CountInfo,
  Foo: {} as Foo,
  FooSubset: {} as FooSubset,
}
