name: Publish
on: 
  workflow_dispatch:
    inputs:
      changes_hash:
        description: Hash of expected changes from lerna publish. Get this by running `yarn changes:hash` locally, or leave blank and check the job's error logs for the expected value.

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_CI_TOKEN }}
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: setup/install/build
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

        yarn
        yarn build

        echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > ~/.npmrc
    - name: publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_CI_TOKEN }}
      run: |
        npm whoami | grep .

        EXPECTED_CHANGES=$(yarn --silent changes:hash)
        if [ "$EXPECTED_CHANGES" != "${{ github.event.inputs.changes_hash }}" ]; then
          echo "Expected hashed changes: $EXPECTED_CHANGES"
          echo "Got: ${{ github.event.inputs.changes_hash }}"
          echo "If the changes printed above look OK, rerun this workflow with the expected hash."
          exit 1
        fi

        yarn lerna publish --yes
